package b29.game;

public enum PhaseStep {
    START_PHASE,
    END_PHASE,

    PLAY_MISSION_TAKEOFF_MOVE_NEXT_ZONE_LANDING,
    PLAY_MISSION_PRESSURIZATION,
    PLAY_MISSION_CONSUME_FUEL,
    PLAY_MISSION_WEATHER,
    PLAY_MISSION_NAVIGATION,
    PLAY_MISSION_RANDOM_EVENT,
    PLAY_MISSION_ABORT_MISSION,
    PLAY_MISSION_FORMATION_ASSEMBLY,
    PLAY_MISSION_FIGHTER_ESCORT_RENDEZVOUS,
    PLAY_MISSION_FIGHTER_RESISTANCE,
    PLAY_MISSION_FIGHTER_ATTACK_B29_CHOOSE_DEFENSIVE_FIRE,
    PLAY_MISSION_FIGHTER_ATTACK_B29_DEFENSIVE_FIRE,
    PLAY_MISSION_FIGHTER_ATTACK_OFFENSIVE_FIRE,
    PLAY_MISSION_FIGHTER_ATTACK_B29_DAMAGE,
    PLAY_MISSION_BOMB_RUN_FLAK,
    PLAY_MISSION_BOMB_RUN,
    PLAY_MISSION_LANDING
}
