package b29.game.mission;

public enum RandomEvent {
    FOOD_POISONING,
    CFC_SYSTEM_FAILS,
    EXCEPTIONAL_FUEL_MANAGEMENT_BY_ENGINEER,
    STORM_SYSTEM_ENCOUNTERED,
    PATHFINDER,
    SLOPPY_FUEL_MANAGEMENT_BY_ENGINEER,
    PICKLE_BARREL,
    HIGH_PRESSURE_SYSTEM_ENCOUNTERED,
    RADAR_SYSTEM_FAILS,
    SEVERE_ICING,
    SHARPSHOOTER
}
