package b29.game.mission;

public enum TakeoffAccident {
    PLANE_CRASHES_AND_EXPLODES_ALL_KIA,
    PLANE_CRASHES_ROLL_FOR_CREW,
    CREW_SAFE_B29_IRREPAIRABLY_DAMAGED,
    CREW_SAFE_B29_REPAIRABLE
}
