package b29.game.mission;

public enum Target {
    IWO_JIMA("Iwo Jima"),
    NAGOYA("Nagoya"),
    AKASHI("Akashi"),
    TOKYO("Tokyo"),
    OTA("Ota"),
    KOBE("Kobe"),
    OKINAWA("Okinawa"),
    YAWATA("Yawata"),
    YOKOHAMA("Yokohama"),
    OSAKA("Osaka"),
    KAWASAKI("Kawasaki"),
    AMAGASAKI("Amagasaki"),
    KANOYA("Kanoya"),
    KOKUBU("Kokubu"),
    MIYAZAKI("Miyazaki"),
    MIYAKONOJO("Miyakonojo"),
    KANOYA_EAST("Kanoya East"),
    HANDA("Handa"),
    EITOKU("Eitoku"),
    KORIYAMA("Koriyama"),
    IZUMI("Izumi"),
    KUSHIRA("Kushira"),
    NITTAGAHARA("Nittagahara"),
    USA("Usa"),
    SAEKI("Saeki"),
    MATSUYAMA("Matsuyama"),
    TOMITAKA("Tomitaka"),
    IBUSUKI("Ibusuki"),
    TACHIARAI("Tachiarai"),
    OITA("Oita"),
    CHIRAN("Chiran"),
    OMURA("Omura"),
    KAGAMIGAHARA("Kagamigahara"),
    SHIZUOKA("Shizuoka"),
    KURE("Kure"),
    NARAO("Narao"),
    OGIKUBU("Ogikubu"),
    OMIYA("Omiya"),
    TOMIOKA("Tomioka"),
    CHIBA("Chiba"),
    HIMEJI("Himeji"),
    MIZUSHIMA("Mizushima"),

    NIIGATA("Niigata"),
    HAMAMATSU("Hamamatsu"),
    YOKKAICHII("Tokkaichii"),
    TOYOHASHI("Toyohashi"),
    FUKUOKA("Fukuoka"),
    OKAYAMA("Okayama"),
    SASEBO("Sasebo"),
    MOJI("Moji"),
    NOBEOKA("Nobeoka"),
    KUMAMATO("Kumamato"),
    UBE("Ube"),
    SHIMONOSEKI("Shimonoseki"),
    KOCHI("Kochi"),
    TAKAMATSU("Takamatsu"),
    TOKUSHIMA("Tokushima"),
    SHIMIZU("Shimizu"),
    KOFU("Kofu"),
    SENDAI("Sendai"),
    SAKAI("Sakai"),
    WAKAYAMA("Wakayami"),
    GIFU("Gifu"),
    UTSUNOMIYA("Utsunomiya"),
    ICHINOMIYA("Ichinomiya"),
    TSURUGA("Tsuruga"),
    UWAJIMA("Uwajima"),
    NAMAZU("Namazu"),
    KUWANA("Kuwana"),
    HIRATSUKA("Hiratsuka"),
    FUKUI("Fukui"),
    KOKURA("Kokura"),

    HIROSHIMA("Hiroshima"),
    OKAZAKI("Okazaki"),
    TOKUYAMA("Tokuyama"),
    OMUTA("Omuta"),
    TSU("Tsu"),
    AOMORI("Aomori"),
    UJI_YAMADA("Uji-Yamada"),
    OGAKI("Ogaki"),
    HACHIOJI("Hachioji"),
    TOYAMA("Toyama"),
    NAGAOKA("Nagaoka"),
    MITO("Mito"),
    SAGA("Saga"),
    MAEBASHI("Maebashi"),
    NISHINOMIYA("Nishinomiya"),
    MIKAGE("Mikage"),
    IMABARI("Imabari"),
    FUKUYAMA("Fukuyama"),
    KUMAGAYA("Kumagaya"),
    ISEZAKI("Isezaki"),
    CHOSHI("Choshi"),
    KAGOSHIMA("Kagoshima"),
    HITACHI("Hitachi"),
    KUSHIKINO("Kushikino"),
    AKITA("Akita"),
    KANSAI("Kansai"),
    KUDAMATSU("Kudamatsu"),
    OSHIMA("Oshima"),
    NAGASAKI("Nagasaki"),
    KYOTO("Kyoto");

    private String name;

    Target(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public String toString() {
        return this.name;
    }
}